# Deploy to Firebase Hosting on merge (no build)
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: show repo contents in the log (debugging)
      - run: ls -la

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_Q3434234_SK_2024_B38B6 }}
          channelId: live
          projectId: q3434234-sk-2024-b38b6